run:
  skip-dirs:
    - client

issues:
  exclude-rules:
    - path: "_test.go$"
      text: "is too long"
      linters:
        - funlen
    - path: "grammar.go$"
      linters:
        - tagalign
        - govet

linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
      #- execinquery
    #- exhaustive
    #- exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
      #- gci
    - ginkgolinter
    - gocheckcompilerdirectives
      #- gochecknoglobals
    - gochecknoinits
    - gochecksumtype
      # - gocognit
    - goconst
    - gocritic
    - godot
      # - godox
      #- goerr113
    - gofmt
    - goheader
    - goimports
    #- gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
      #- ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    #- nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
